name: CI_action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, development]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare backend
        run: npm run prepare-backend
      - name: Prepare frontend
        run: npm run prepare-frontend
      - name: Run the tests
        run: npm test
